project_id = "kswmiuiqwlbavlmzasnz"

[functions.voice-nlp]
verify_jwt = false

[functions.cognitive-analysis]
verify_jwt = false

[functions.voice-assistant]
verify_jwt = false

[functions.analyze-user-patterns]
verify_jwt = false

[functions.send-caregiver-reminder]
verify_jwt = false

[functions.alexa-skill]
verify_jwt = false

[functions.caregiver-support]
verify_jwt = false

[functions.extract-voice-reminder]
verify_jwt = false
